name = "LeidenClustering"
uuid = "945644f9-d231-49e7-b336-a4cd00f5784c"
authors = ["Eric Martin Feltham <eric.feltham@aya.yale.edu>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
BenchmarkTools = "1.6.0"
CSV = "0.10.15"
DataFrames = "1.7.0"
Graphs = "1.13.0"
Random = "1.11.0"
Revise = "3.8.1"
SimpleWeightedGraphs = "1.5.0"
SparseArrays = "1.11.0"
